M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Wed 11 Sep 2024 15:53:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-11T15:53:45+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.3386Y-3.8189
T2
X5.7736Y-4.1339
X6.2736Y-4.1339
T3
X5.2088Y-4.0348
X5.2088Y-4.1348
T0
M30
